### ISSUE TITLE
n4js-start failed with error connection refused

### ISSUE THREAD

**Issue by stardiviner** [tmtxt/n4js.el#3]
Here is the buffer output:

    ERROR (-v for expanded information):
    	Connection refused
    
     -host      Domain name or IP of host to connect to (default: localhost)
     -port      Port of host to connect to (default: 1337)
     -name      RMI name, i.e. rmi://<host>:<port>/<name> (default: shell)
     -pid       Process ID to connect to
     -c         Command line to execute. After executing it the shell exits
     -file      File containing commands to execute, or '-' to read from stdin. After executing it the shell exits
     -readonly  Connect in readonly mode (only for connecting with -path)
     -path      Points to a neo4j db path so that a local server can be started there
     -config    Points to a config file when starting a local server
    
    Example arguments for remote:
    	-port 1337
    	-host 192.168.1.234 -port 1337 -name shell
    	-host localhost -readonly
    	...or no arguments for default values
    Example arguments for local:
    	-path /path/to/db
    	-path /path/to/db -config /path/to/neo4j.config
    	-path /path/to/db -readonly
    
    Process neo4j-shell exited abnormally with code 1

**Comment by stardiviner** [comment]
I fixed it, it is because neo4j server not started correctly. I enable local shell access in config file. Now it works. Thanks for you project @tmtxt

**Comment by tmtxt** [comment]
yeah I didn’t realise that I have an issue for this 😛

**Comment by stardiviner** [comment]
Yeah, My Github notifications sometimes will not get update on my repos neither. I experienced that too.
